import { GoogleSpreadsheet } from "google-spreadsheet";
import { JWT } from 'google-auth-library';

console.log('credentials', process.env.NEXT_PUBLIC_GOOGLE_SHEETS_CREDENTIALS);

const serviceAccountAuth = new JWT({
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    email: "guestlist@moosbu.iam.gserviceaccount.com",
    key: "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDI8hmmEf3mEoKz\nLbloiUAZoO4UYj5uu0K28plICiyGewMKCd0DkFQsuiK4avx93XSgtOJnCUz6CD/y\nCABaZoeF9+QN9kfeY8Fj7E0EBYlve8bNUbeit0XzT91rdG+FXbV/smPiGARoPv4T\nN+xComUMBffESmH2PbxYNkejM0tZUx5i7R0qhiLlRsqOoaU7OX05DCynDsp91BRF\n+YZtnezi6hVLAh2UffoLCS3yVA59rGoRYpFyiG8bjU2F7kpVfY3yDXMJpAt47ImT\n0Mh1xeE3/QUhPGpMwOFyP1f/OMA/dYp5L80xmL/J6g4T6CD6YNd0j+fEDrN0OVDl\nvWo3ON/ZAgMBAAECggEAQS7fiRJvBRHeGddsPG/BPk8Iy83uqKbQBl59wHOka989\nZiU672wDEhszJhV2YDHVIkhq5LeMo9LHQ3C7BJgbwCZgcPMB7y72zb4aYYKWSXai\nT3oBkqPW6g1vKuszPdTfClRIuE/IJjTA4GUUm6zoEFVjQOZMDr+J+CdrZ5I9D/Ul\nxWnhfJGmaUSYjcx7G4pm6KJD/djeDFO3W+qhYMNakE6yM8b8pDPSbTpUhOLszwMi\nQTD7LWPNhPhUzwsJFi2Wy9LVkV0EZDFFM8Q4CGo3F1m2PXY/nPDu1p2jpHHZaaRr\nMgJKvV8cMp+ecTRR4RFYIkn8Ih/nynhrMCC5GWUqDQKBgQD3O4tIJy9pJCiUxJxi\nivvZhQH7Ft1UeuPWNVTnxMooTyVCmRTDVExsqsmWnAna/ZLKfFLmyp3EgE2m/DHA\nfUNTtoODI8/jOF/mSg3SoAoPjpbAnE6/zUe92rL9b+2zxxRuRTZgHaCnCSNHJ/Iv\nhfazhafWqk1zOiq5ucZrlWoqCwKBgQDQEllbEhzT/qoUYUd347ne9hmTYPRNFy8O\nnLDvZWU+K0DoxjcwVJZJpsHKt64Lcxhwpp2ToJJBZgl591s2unzbHsZoN/jQ34gI\ndtdyMlVV+NGN7MjN/s9yR5JlTNb3SFJorSWNBG/SsjU5n54YmTZPMT6F4df2iZqI\nw1I+8l1wKwKBgQCNtPd0d+FY5nzMKJVqdjc8ylwES2q5TWbiFNeBsO4ehJ7auVuJ\nSfw0HQBG71FG0CkfHnt2BZTAWLopiEwMBMBebzKaLCCwIFP3b2LU4x5hJF2MMQuC\nLGt+iqglU85vSSCQw+MS3GiE1Vv/IQpT6vkolOdKx3p1HVX39l+gspeTWQKBgQDC\nN25qwJRiGUK+dTMVqF4VzReAZq6CytIkzIOnYbjH9+3FmUdoeHwz0VDwnNT7YPp+\nJDfP1cDPBKRx0T617gqfKbG/FAfPR+cdJ3jg4jSfY/qOhGfHSEJwhHgU0E2TUlGB\n3aTAZVTPkYJ3ABO9GD4GW4vlwjIosLarU84QbYBkMwKBgQDBFgzrDrACdcv/9WZj\nredYA9CFJrCi8GZd37gmCht1p7jgbofP4o8n0BG3vBWePjlk3rAqWVsNRw4TRrrH\neRfYEnumX0C0K6fuR3uT4BcbohkYHIJzl2U+ETmniZgmwMWO9VJF6AqnY3/XFdkb\ncsq2DHoYiO37lOx9ZNiYCCg5RA==\n-----END PRIVATE KEY-----\n",
    scopes: ['https://www.googleapis.com/auth/spreadsheets'],
  });

const SPREADSHEET_ID = '1qqfCXpwTYZb0VBXnS8w-NOdM_BU6G-ZVp_lkgFOa7mw';

export async function getSheet() {
  const doc = new GoogleSpreadsheet(SPREADSHEET_ID, serviceAccountAuth);
  await doc.loadInfo();
  return doc.sheetsByIndex[0];
}